"""
Django settings for Proyecto_RTDF project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b$%#mw8_62v-q!t9(9noi_xo(5&fjnq(s^(q0%1*rp@#3f5-=)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



# CONFIGURACIOIN DE ENTORNO -------------
    # Felipe = local_felipe
    # Francisco = local_francisco
    # Nicolas =  local_nico
    # PythonAnywhere = pa

entorno = 'local_nico'

if entorno == "local_felipe":

    host= '127.0.0.1'
    db_name= 'rtdf_beta'
    db_user= 'root'
    db_pw= 'practica'
    db_host= 'localhost'


elif entorno == "local_francisco":

    host= '127.0.0.1'
    db_name= 'rtdf_data'
    db_user= 'root'
    db_pw= 'admin'
    db_host= 'localhost'

elif entorno == "local_nico":

    host= '127.0.0.1'
    db_name= 'rtdf_data_final'
    db_user= 'root'
    db_pw= 'nico123'
    db_host= 'localhost'

elif entorno == 'pa':

    host= 'farmaciadigital.pythonanywhere.com'
    db_name= 'farmaciadigital$rtdf_final'
    db_user= 'farmaciadigital'
    db_pw= 'rtdfdev2023'
    db_host= 'farmaciadigital.mysql.pythonanywhere-services.com'

elif entorno == 'capstone':

    host= 'RTDFCapstone.pythonanywhere.com'
    db_name= 'RTDFCapstone$rtdf_final'
    db_user= 'RTDFCapstone'
    db_pw= 'rtdfdev2023'
    db_host= 'RTDFCapstone.mysql.pythonanywhere-services.com'

else:

    raise ValueError(f"Entorno desconocido: {entorno}")


ALLOWED_HOSTS = [host]

MESSAGE_STORAGE = "django.contrib.messages.storage.cookie.CookieStorage"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rtdf',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Proyecto_RTDF.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Proyecto_RTDF.wsgi.application'


AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  
)

AUTH_USER_MODEL = 'rtdf.Usuario'  # Reemplaza 'tu_app' con el nombre de tu aplicación

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases


# configuración de la base de datos por entorno

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': db_name,
        'USER': db_user,
        'PASSWORD': db_pw,
        'HOST': db_host,
        'PORT': '3306',
        'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"},
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "media",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL='/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = 'login'  # Esta es la URL de inicio de sesión que has definido


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = "permify.practica@gmail.com"
EMAIL_HOST_PASSWORD = "bnwm ctbi dxsh cqny"