# Generated by Django 4.0.6 on 2023-09-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
