# Generated by Django 4.0.6 on 2023-09-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0002_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistro',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
