# Generated by Django 4.0.6 on 2023-09-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0003_alter_preregistro_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grbas',
            old_name='grado_disfonia',
            new_name='g_grado_disfonia',
        ),
        migrations.RenameField(
            model_name='rasati',
            old_name='aspereza',
            new_name='a_aspereza',
        ),
        migrations.RenameField(
            model_name='rasati',
            old_name='astenia',
            new_name='a_astenia',
        ),
        migrations.RenameField(
            model_name='rasati',
            old_name='inestabilidad',
            new_name='i_inestabilidad',
        ),
        migrations.RenameField(
            model_name='rasati',
            old_name='ronquedad',
            new_name='r_ronquedad',
        ),
        migrations.RenameField(
            model_name='rasati',
            old_name='soplo',
            new_name='s_soplo',
        ),
        migrations.RenameField(
            model_name='rasati',
            old_name='tension',
            new_name='t_tension',
        ),
        migrations.AlterField(
            model_name='preregistro',
            name='ap_materno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='preregistro',
            name='password',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ap_materno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
