# Generated by Django 4.0.6 on 2023-09-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0005_rename_timestamp_audio_fecha_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistro',
            name='validado',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_comuna',
            field=models.ForeignKey(db_column='id_comuna', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rtdf.comuna'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_tp_usuario',
            field=models.ForeignKey(db_column='id_tp_usuario', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rtdf.tpusuario'),
        ),
    ]
