# Generated by Django 4.0.6 on 2023-09-04 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0006_alter_preregistro_validado_alter_usuario_id_comuna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_comuna',
            field=models.ForeignKey(db_column='id_comuna', default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='rtdf.comuna'),
        ),
    ]
