# Generated by Django 4.0.6 on 2023-09-05 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0007_alter_usuario_id_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_comuna',
            field=models.ForeignKey(db_column='id_comuna', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rtdf.comuna'),
        ),
    ]
