# Generated by Django 4.0.6 on 2023-09-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0008_alter_usuario_id_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Paciente', 'Paciente'), ('Familiar', 'Familiar'), ('Fonoaudiologo', 'Fonoaudiologo'), ('Neurologo', 'Neurologo'), ('Enfermera', 'Enfermera')], max_length=30),
        ),
    ]
