# Generated by Django 4.0.6 on 2023-09-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0009_alter_tpusuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Paciente', 'Paciente'), ('Fonoaudiologo', 'Fonoaudiologo'), ('Familiar', 'Familiar'), ('Enfermera', 'Enfermera'), ('Neurologo', 'Neurologo')], max_length=30),
        ),
    ]
