# Generated by Django 4.0.6 on 2023-09-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0011_usuario_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_tp_usuario',
            field=models.ForeignKey(db_column='id_tp_usuario', default=1, on_delete=django.db.models.deletion.CASCADE, to='rtdf.tpusuario'),
        ),
    ]
