# Generated by Django 4.0.6 on 2023-09-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0013_alter_tpusuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[(1, 1), (2, '2'), (3, 'Fonoaudiologo'), (4, 'Familiar'), (5, 'Enfermera'), (6, 'Neurologo')], max_length=30),
        ),
    ]
