# Generated by Django 4.0.6 on 2023-09-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0016_alter_tpusuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='nombre_institucion',
            field=models.CharField(max_length=50),
        ),
    ]
