# Generated by Django 4.0.6 on 2023-09-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0017_alter_institucion_nombre_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpusuario',
            name='tipo_usuario',
            field=models.CharField(max_length=30),
        ),
    ]
