# Generated by Django 4.0.6 on 2023-09-21 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0018_alter_tpusuario_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TpFamiliar',
            fields=[
                ('id_tipo_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_familiar', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tipo_familiar',
            },
        ),
        migrations.AddField(
            model_name='familiarpaciente',
            name='fk_tipo_familiar',
            field=models.ForeignKey(db_column='fk_tipo_familiar', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rtdf.tpfamiliar'),
        ),
    ]
