# Generated by Django 4.0.6 on 2023-09-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0019_tpfamiliar_familiarpaciente_fk_tipo_familiar'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tpfamiliar',
            table='tp_familiar',
        ),
    ]
