# Generated by Django 4.0.6 on 2023-09-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0020_alter_tpfamiliar_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiarpaciente',
            name='parentesco',
        ),
    ]
