# Generated by Django 4.0.6 on 2023-09-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0023_alter_audio_options_alter_audioscoeficientes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'verbose_name_plural': 'audio'},
        ),
        migrations.AlterModelOptions(
            name='audioscoeficientes',
            options={'verbose_name_plural': 'audiocoeficiente'},
        ),
        migrations.AlterModelOptions(
            name='comuna',
            options={'verbose_name_plural': 'comuna'},
        ),
        migrations.AlterModelOptions(
            name='esv',
            options={'verbose_name_plural': 'esv'},
        ),
        migrations.AlterModelOptions(
            name='familiarpaciente',
            options={'verbose_name_plural': 'familiar paciente'},
        ),
        migrations.AlterModelOptions(
            name='grbas',
            options={'verbose_name_plural': 'grbas'},
        ),
        migrations.AlterModelOptions(
            name='informe',
            options={'verbose_name_plural': 'informe'},
        ),
        migrations.AlterModelOptions(
            name='institucion',
            options={'verbose_name_plural': 'institucion'},
        ),
        migrations.AlterModelOptions(
            name='intensidad',
            options={'verbose_name_plural': 'intensidad'},
        ),
        migrations.AlterModelOptions(
            name='origenaudio',
            options={'verbose_name_plural': 'origen audio'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name_plural': 'paciente'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'país'},
        ),
        migrations.AlterModelOptions(
            name='pautaterapeutica',
            options={'verbose_name_plural': 'Pauta terapéutica'},
        ),
        migrations.AlterModelOptions(
            name='preregistro',
            options={'verbose_name_plural': 'pre registro'},
        ),
        migrations.AlterModelOptions(
            name='profesionalsalud',
            options={'verbose_name_plural': 'profesional salud'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name_plural': 'provincia'},
        ),
        migrations.AlterModelOptions(
            name='rasati',
            options={'verbose_name_plural': 'rasati'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'región'},
        ),
        migrations.AlterModelOptions(
            name='registros',
            options={'verbose_name_plural': 'registro'},
        ),
        migrations.AlterModelOptions(
            name='relacionfp',
            options={'verbose_name_plural': 'relación familiar paciente'},
        ),
        migrations.AlterModelOptions(
            name='relacionpapro',
            options={'verbose_name_plural': 'relación profesional paciente'},
        ),
        migrations.AlterModelOptions(
            name='tipodiabetes',
            options={'verbose_name_plural': 'tipo diabetes'},
        ),
        migrations.AlterModelOptions(
            name='tipohipertension',
            options={'verbose_name_plural': 'tipo hipertensión'},
        ),
        migrations.AlterModelOptions(
            name='tpfamiliar',
            options={'verbose_name_plural': 'tipo familiar'},
        ),
        migrations.AlterModelOptions(
            name='tpinforme',
            options={'verbose_name_plural': 'tipo informe'},
        ),
        migrations.AlterModelOptions(
            name='tpllenado',
            options={'verbose_name_plural': 'tipo llenado'},
        ),
        migrations.AlterModelOptions(
            name='tpterapia',
            options={'verbose_name_plural': 'tipo terapia'},
        ),
        migrations.AlterModelOptions(
            name='tpusuario',
            options={'verbose_name_plural': 'tipo usuario'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'usuario'},
        ),
        migrations.AlterModelOptions(
            name='validacion',
            options={'verbose_name_plural': 'validación'},
        ),
        migrations.AlterModelOptions(
            name='vocalizacion',
            options={'verbose_name_plural': 'vocalización'},
        ),
    ]
