# Generated by Django 4.0.6 on 2023-09-27 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0024_alter_audio_options_alter_audioscoeficientes_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pautaterapeutica',
            name='fk_relacion_pa_pro',
        ),
        migrations.AddField(
            model_name='pautaterapeutica',
            name='fk_informe',
            field=models.ForeignKey(db_column='fk_informe', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rtdf.informe'),
        ),
    ]
