# Generated by Django 4.0.6 on 2023-09-27 13:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0025_remove_pautaterapeutica_fk_relacion_pa_pro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_comuna',
            field=models.ForeignKey(db_column='id_comuna', default=1, on_delete=django.db.models.deletion.PROTECT, to='rtdf.comuna'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_tp_usuario',
            field=models.ForeignKey(db_column='id_tp_usuario', default=1, on_delete=django.db.models.deletion.PROTECT, to='rtdf.tpusuario'),
        ),
    ]
