# Generated by Django 4.0.6 on 2023-09-27 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0026_alter_informe_fecha_alter_usuario_id_comuna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
