# Generated by Django 4.0.6 on 2023-09-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0027_alter_informe_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
