# Generated by Django 4.0.6 on 2023-09-27 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0028_alter_informe_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esv',
            name='id_informe',
            field=models.OneToOneField(db_column='id_informe', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rtdf.informe'),
        ),
        migrations.AlterField(
            model_name='grbas',
            name='id_informe',
            field=models.OneToOneField(db_column='id_informe', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rtdf.informe'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='fk_relacion_pa_pro',
            field=models.ForeignKey(db_column='fk_relacion_pa_pro', on_delete=django.db.models.deletion.PROTECT, to='rtdf.relacionpapro'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='id_audio',
            field=models.ForeignKey(blank=True, db_column='id_audio', null=True, on_delete=django.db.models.deletion.PROTECT, to='rtdf.audio'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='tp_informe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rtdf.tpinforme'),
        ),
        migrations.AlterField(
            model_name='rasati',
            name='id_informe',
            field=models.OneToOneField(db_column='id_informe', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rtdf.informe'),
        ),
    ]
