# Generated by Django 4.0.6 on 2023-09-27 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0029_alter_esv_id_informe_alter_grbas_id_informe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pautaterapeutica',
            name='fk_informe',
            field=models.ForeignKey(db_column='fk_informe', default=1, on_delete=django.db.models.deletion.CASCADE, to='rtdf.informe'),
        ),
        migrations.AlterField(
            model_name='pautaterapeutica',
            name='fk_tp_terapia',
            field=models.ForeignKey(db_column='fk_tp_terapia', on_delete=django.db.models.deletion.PROTECT, to='rtdf.tpterapia'),
        ),
    ]
