# Generated by Django 4.0.6 on 2023-10-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0031_alter_audio_fk_origen_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intensidad',
            name='max_db',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intensidad',
            name='min_db',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
