# Generated by Django 4.0.6 on 2023-10-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0032_alter_intensidad_max_db_alter_intensidad_min_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocalizacion',
            name='tempo',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
